spring:
  application:
    name: "kstream-sample"
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: "dev"

kafka:
  serviceUri: public-kstreams-issue-avaya-d337.aivencloud.com:25624
  username: avnadmin
  password: AVNS_zXgiM9f7u2TB1WqA2T3
  schemaRegistryUri: https://avnadmin:AVNS_zXgiM9f7u2TB1WqA2T3@public-kstreams-issue-avaya-d337.aivencloud.com:25615

app:
  inputTopic: input-topic
  outputTopic: output-topic