name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  increment-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install semver-tool
        run: |
          mkdir -p ~/bin
          curl -L https://github.com/fsaintjacques/semver-tool/archive/3.4.0.tar.gz | tar xz -C ~/bin
          wget -O ~/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          echo "~/bin" >> $GITHUB_PATH

      - name: Get next release branch
        id: new_branch
        run: |
          LATEST_RELEASE_VERSION=$(git branch -r | grep 'origin/release-' | sort -V | tail -n 1 | sed 's/origin\///')
          if [ -z "$LATEST_RELEASE_VERSION" ]; then
            echo "No release-* branch found."
            NEXT_RELEASE_VERSION="0.0.0"
          else
            echo "Latest release version: $LATEST_RELEASE_VERSION"
            NEXT_RELEASE_VERSION=$(semver -i patch $LATEST_RELEASE_VERSION)
          fi
          echo "Next release version: $NEXT_RELEASE_VERSION"
          echo "branch=release-${NEXT_RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Create new release branch
        run: |
          NEW_RELEASE_BRANCH=release-${{ steps.new_branch.outputs.branch }}
          echo "Creating new release branch: $NEW_RELEASE_BRANCH"
          git checkout -b ${NEW_RELEASE_BRANCH}
          git push -u origin ${NEW_RELEASE_BRANCH}
