name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  increment-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install semver-tool
        run: |
          mkdir -p $HOME/.local/bin/
          wget -O $HOME/.local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x $HOME/.local/bin/semver
          echo "$HOME/.local/bin/" >> $GITHUB_PATH

      - name: Get next release branch
        id: new_branch
        run: |
          LATEST_RELEASE_VERSION=$(git branch -r | grep 'origin/release-' | sort -V | tail -n 1 | sed 's/origin\/release-//' | tr -d '[:space:]')
          if [ -z "$LATEST_RELEASE_VERSION" ]; then
            echo "No release-* branch found."
            NEXT_RELEASE_VERSION="0.0.0"
          else
            echo "Latest release version: $LATEST_RELEASE_VERSION"
            NEXT_RELEASE_VERSION=$(semver -i patch $LATEST_RELEASE_VERSION)
          fi
          echo "Next release version: $NEXT_RELEASE_VERSION"
          echo "next_version=${NEXT_RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Create new release branch
        run: |
          NEW_RELEASE_BRANCH=release-${{ steps.new_branch.outputs.next_version }}
          echo "Creating new release branch: ${NEW_RELEASE_BRANCH}"
          git checkout -b ${NEW_RELEASE_BRANCH}
          git push -u origin ${NEW_RELEASE_BRANCH}
          echo "Created new release branch ${NEW_RELEASE_BRANCH}" >> $GITHUB_STEP_SUMMARY
